apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "pinger-files"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  volumeName: "pinger-files-pv"
